###########################
## StarterChest - Config ##
###########################
#
# This is the main configuration file of StarterChest.
#

database:
  # What type of database should we use? (Allowed database types: 'mysql' or 'yaml'
  # If you use MySQL as database, then please enter a host, a port, a database name, an username and an userpassword.
  # It is recommened that you create a new database for StarterChest
  type: 'yaml'
  
  host: ''
  port : ''
  databasename: ''
  username: ''
  password: ''
  