name: StarterChest
version: 1.0
author: matzefratze123
description: Powerful starting chest plugin for Bukkit.

main: com.matzefratze123.starterchest.StarterChest

commands:
  starterchest:
    description: General StarterChest command.
    aliases: [sc, schest]